title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
google_analytics:
remote_theme: zendesk/jekyll-theme-zendesk-garden@main
sidebar:
  - introducing-datamapper
